<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_blockchain</name>
   <tag></tag>
   <elementGuidId>5012de9e-9678-48d3-914c-152f7668d0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-rb-event-key='/blockchain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-rb-event-key='/blockchain']</value>
      <webElementGuid>68ef46d5-21f4-45df-ae35-eeeae8411ddd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
